# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vistaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 607)
        MainWindow.setStyleSheet("background-color: rgb(29, 46, 64);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 651, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 510, 691, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.radioEta = QtWidgets.QRadioButton(self.centralwidget)
        self.radioEta.setGeometry(QtCore.QRect(80, 280, 281, 20))
        self.radioEta.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.radioEta.setCheckable(True)
        self.radioEta.setChecked(True)
        self.radioEta.setAutoExclusive(False)
        self.radioEta.setObjectName("radioEta")
        self.radioUmbral = QtWidgets.QRadioButton(self.centralwidget)
        self.radioUmbral.setGeometry(QtCore.QRect(460, 280, 181, 20))
        self.radioUmbral.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.radioUmbral.setCheckable(True)
        self.radioUmbral.setChecked(True)
        self.radioUmbral.setAutoExclusive(False)
        self.radioUmbral.setObjectName("radioUmbral")
        self.botonPrecision = QtWidgets.QPushButton(self.centralwidget)
        self.botonPrecision.setGeometry(QtCore.QRect(120, 430, 231, 31))
        self.botonPrecision.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.botonPrecision.setObjectName("botonPrecision")
        self.botonPerdida = QtWidgets.QPushButton(self.centralwidget)
        self.botonPerdida.setGeometry(QtCore.QRect(420, 430, 231, 31))
        self.botonPerdida.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.botonPerdida.setObjectName("botonPerdida")
        self.a = QtWidgets.QLabel(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(90, 120, 251, 31))
        self.a.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.a.setObjectName("a")
        self.a_2 = QtWidgets.QLabel(self.centralwidget)
        self.a_2.setGeometry(QtCore.QRect(400, 120, 311, 31))
        self.a_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.a_2.setObjectName("a_2")
        self.inputEta = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEta.setGeometry(QtCore.QRect(90, 200, 251, 31))
        self.inputEta.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.inputEta.setObjectName("inputEta")
        self.inputGeneraciones = QtWidgets.QLineEdit(self.centralwidget)
        self.inputGeneraciones.setGeometry(QtCore.QRect(430, 200, 251, 31))
        self.inputGeneraciones.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.inputGeneraciones.setObjectName("inputGeneraciones")
        self.score = QtWidgets.QLabel(self.centralwidget)
        self.score.setGeometry(QtCore.QRect(100, 340, 571, 41))
        self.score.setText("")
        self.score.setObjectName("score")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Red Neuronal Para Predecir Si El Cáncer Es Maligno O Benigno"))
        self.label_2.setText(_translate("MainWindow", "Enlace Al Dataset Empleado: https://www.kaggle.com/uciml/breast-cancer-wisconsin-data"))
        self.radioEta.setText(_translate("MainWindow", "Mejor Taza De Aprendizaje (0.01)"))
        self.radioUmbral.setText(_translate("MainWindow", "Generaciones (100)"))
        self.botonPrecision.setText(_translate("MainWindow", "Precision De Los Datos"))
        self.botonPerdida.setText(_translate("MainWindow", "Perdida De Los Datos"))
        self.a.setText(_translate("MainWindow", "Ingrese taza de aprendizaje"))
        self.a_2.setText(_translate("MainWindow", "Ingrese Numero De Generaciones"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
